import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Upload, CheckCircle, MapPin, User, MessageSquare, ShieldCheck, Download, Printer, Share2, Info, Sparkles, Navigation, Send, Zap, Clock } from "lucide-react";
import { submitFIR, getFIRById } from "../lib/api";
import { toast } from "sonner";

const ComplaintForm = () => {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ name: "", telegram: "", location: "", description: "" });
  const [isTriggering, setIsTriggering] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [showTracking, setShowTracking] = useState(false);
  const [lodgedFIRId, setLodgedFIRId] = useState<string | null>(null);
  const [currentStatus, setCurrentStatus] = useState<string>("Active");
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  useEffect(() => {
    handleAutoLocation();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await submitFIR({
        ...form,
        reporter: form.name,
        type: "General Report"
      });
      if (response.success) {
        setLodgedFIRId(response.fir.id);
        setCurrentStatus(response.fir.status);
        setSubmitted(true);
        toast.success("E-FIR Generated Successfully");
      }
    } catch (err) {
      toast.error("Failed to submit FIR. Network error.");
    }
  };

  const handleAutoLocation = () => {
    if ("geolocation" in navigator) {
      toast.info("Accessing neural positioning...");
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setForm(prev => ({ ...prev, location: `Lat: ${position.coords.latitude.toFixed(4)}, Lng: ${position.coords.longitude.toFixed(4)} (Detected)` }));
          toast.success("Location synchronized");
        },
        () => {
          toast.error("Location access denied. Please enter manually.");
        }
      );
    }
  };

  const handleAutoWrite = () => {
    const mockReports = [
      "Suspicious activity observed near the shopping complex. A group of individuals were seen loitering after hours and attempting to bypass security gates.",
      "Bag left unattended near the metro station entrance. Reporting as a potential safety hazard for immediate inspection by local units.",
      "Witnessed a hit and run incident involving a silver sedan. Vehicle headed North toward MG Road. No immediate injuries but property damage occurred.",
    ];
    const report = mockReports[Math.floor(Math.random() * mockReports.length)];
    setForm(prev => ({ ...prev, description: report }));
    toast.success("Incident report generated by AI");
  };

  const handleTriggerWebhook = async () => {
    if (!form.telegram) {
      toast.error("Please provide a Telegram number first.");
      return;
    }
    
    setIsTriggering(true);
    const PROXY_URL = "http://localhost:5000/api/trigger-webhook";
    
    try {
      const response = await fetch(PROXY_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...form,
          timestamp: new Date().toISOString(),
          source: "GuardianNet Portal"
        })
      });
      
      if (response.ok) {
        toast.success("Automation triggered successfully!");
      } else {
        toast.error("Webhook endpoint returned an error.");
      }
    } catch (err) {
      toast.error("Failed to reach automation server. Check ngrok status.");
    } finally {
      setIsTriggering(false);
    }
  };

  const handleFileUpload = () => {
    setIsUploading(true);
    setTimeout(() => setIsUploading(false), 1500);
  };

  const firNumber = `FIR-2026-${Math.floor(Math.random() * 90000) + 10000}`;
  const timestamp = new Date().toLocaleString();

  return (
    <section id="complaint" className="section-padding relative overflow-hidden">
      <div className="absolute top-0 right-0 w-64 h-64 bg-primary/10 blur-[100px] -z-10 animate-float"></div>
      
      <div className="container mx-auto px-4 md:px-8 max-w-5xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-primary text-[10px] font-black uppercase tracking-widest mb-4">
            <ShieldCheck size={12} />
            E-GOVERNANCE PORTAL
          </div>
          <h2 className="text-4xl md:text-5xl font-black mb-6 tracking-tight">
            Digital <span className="text-gradient">FIR System</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto leading-relaxed">
            Report incidents instantly and securely. Our AI-driven system generates an official FIR record within seconds.
          </p>
        </motion.div>

        <AnimatePresence mode="wait">
          {!submitted ? (
            <motion.div
              key="form-container"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              className="grid lg:grid-cols-5 gap-8 bg-slate-50 border border-primary/20 rounded-[2.5rem] p-4 md:p-8 shadow-xl"
            >
              <div className="lg:col-span-3 space-y-6">
                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-xs font-black text-muted-foreground uppercase tracking-widest ml-1">Full Name</label>
                      <div className="relative group">
                        <User className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                        <input
                          required
                          value={form.name}
                          onChange={(e) => setForm({ ...form, name: e.target.value })}
                          className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white border border-primary/20 text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-primary/20 focus:border-primary/50 outline-none transition-all shadow-sm"
                          placeholder="Ex: Kavya Sri"
                        />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <div className="flex justify-between items-center ml-1">
                        <label className="text-xs font-black text-muted-foreground uppercase tracking-widest">Incident Location</label>
                        <button 
                          type="button"
                          onClick={handleAutoLocation}
                          className="text-[10px] font-black text-primary hover:text-white transition-all uppercase flex items-center gap-1"
                        >
                          <Navigation size={10} /> Auto-Detect
                        </button>
                      </div>
                      <div className="relative group">
                        <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                        <input
                          required
                          value={form.location}
                          onChange={(e) => setForm({ ...form, location: e.target.value })}
                          className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white/5 border border-white/10 text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-primary/20 focus:border-primary/50 outline-none transition-all"
                          placeholder="Ex: Banjara Hills, Hyderabad"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-xs font-black text-muted-foreground uppercase tracking-widest ml-1">Telegram Number</label>
                    <div className="relative group">
                      <Send className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                      <input
                        required
                        type="text"
                        value={form.telegram}
                        onChange={(e) => setForm({ ...form, telegram: e.target.value })}
                        className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white/5 border border-white/10 text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-primary/20 focus:border-primary/50 outline-none transition-all"
                        placeholder="Ex: +91 98765 43210"
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between items-center ml-1">
                      <label className="text-xs font-black text-muted-foreground uppercase tracking-widest">Incident Description</label>
                      <button 
                        type="button"
                        onClick={handleAutoWrite}
                        className="text-[10px] font-black text-cyan-400 hover:text-white transition-all uppercase flex items-center gap-1"
                      >
                        <Sparkles size={10} /> Auto-Write
                      </button>
                    </div>
                    <div className="relative group">
                      <MessageSquare className="absolute left-4 top-5 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
                      <textarea
                        required
                        rows={4}
                        value={form.description}
                        onChange={(e) => setForm({ ...form, description: e.target.value })}
                        className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white border border-primary/20 text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-primary/20 focus:border-primary/50 outline-none resize-none transition-all shadow-sm"
                        placeholder="Please provide specific details about the event..."
                      />
                    </div>
                  </div>

                  <div className="p-6 rounded-2xl border border-dashed border-primary/30 bg-primary/5 flex flex-col items-center justify-center gap-4 text-center group hover:bg-primary/10 transition-all cursor-pointer shadow-sm"
                    onClick={() => fileInputRef.current?.click()}>
                    <input type="file" ref={fileInputRef} className="hidden" onChange={handleFileUpload} />
                    <div className={`p-4 rounded-full bg-primary/10 text-primary ${isUploading ? 'animate-bounce' : 'group-hover:scale-110 transition-transform'}`}>
                      <Upload size={24} />
                    </div>
                    <div>
                      <div className="text-sm font-bold">{isUploading ? 'Uploading Evidence...' : 'Upload Evidence'}</div>
                      <div className="text-[10px] text-muted-foreground font-medium mt-1 uppercase tracking-widest">Images, Video, or Audio (MAX 50MB)</div>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={handleTriggerWebhook}
                    disabled={isTriggering}
                    className="w-full py-5 rounded-2xl bg-white/5 border border-primary/20 text-primary font-black uppercase tracking-widest hover:bg-primary/10 transition-all active:scale-[0.98] flex items-center justify-center gap-3 group overflow-hidden relative"
                  >
                    <div className="absolute inset-0 bg-gradient-to-r from-primary/0 via-primary/5 to-primary/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>
                    <Zap className={`w-5 h-5 ${isTriggering ? 'animate-pulse' : ''}`} />
                    {isTriggering ? 'Triggering...' : 'TRIGGER AUTOMATION WEBHOOK'}
                  </button>

                  <button
                    type="submit"
                    className="w-full py-5 rounded-2xl bg-gradient-to-r from-primary to-cyan-500 text-white font-black uppercase tracking-widest hover:shadow-lg hover:shadow-primary/30 transition-all active:scale-[0.98] flex items-center justify-center gap-3"
                  >
                    <FileText className="w-5 h-5" />
                    GENERATE E-FIR
                  </button>
                </form>
              </div>

              <div className="lg:col-span-2 bg-primary/10 border border-primary/20 rounded-[2rem] p-8 flex flex-col justify-center gap-6">
                <div className="w-14 h-14 rounded-full bg-primary/20 flex items-center justify-center text-primary">
                  <Info size={28} />
                </div>
                <h3 className="text-xl font-black tracking-tight">Instant Verification</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Every FIR filed through the Guardian Net portal is automatically time-stamped, geo-tagged, and encrypted to ensure the integrity of the evidence.
                </p>
                <div className="space-y-4 pt-4 border-t border-primary/10">
                  <div className="flex items-center gap-3 text-xs font-bold">
                    <CheckCircle size={16} className="text-primary" />
                    <span>Instant Digital Record</span>
                  </div>
                  <div className="flex items-center gap-3 text-xs font-bold">
                    <CheckCircle size={16} className="text-primary" />
                    <span>Real-time Officer Assignment</span>
                  </div>
                  <div className="flex items-center gap-3 text-xs font-bold">
                    <CheckCircle size={16} className="text-primary" />
                    <span>Legal ADMISSIBLE Evidence</span>
                  </div>
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="fir-result"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="max-w-2xl mx-auto"
            >
              <div className="text-center mb-8">
                 <div className="w-20 h-20 bg-emerald-500/20 text-emerald-500 rounded-full flex items-center justify-center mx-auto mb-4 animate-bounce">
                   <CheckCircle size={40} />
                 </div>
                 <h3 className="text-3xl font-black mb-2 tracking-tight">E-FIR GENERATED</h3>
                 <p className="text-muted-foreground">Digital record has been securely stored in the central database.</p>
              </div>

              <FIRTrackingModal 
                isOpen={showTracking} 
                onClose={() => setShowTracking(false)} 
                firId={lodgedFIRId} 
                initialStatus={currentStatus}
              />


              <div className="bg-white text-slate-900 rounded-3xl p-8 shadow-2xl relative overflow-hidden font-sans group">
                <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'repeating-linear-gradient(45deg, #000 0, #000 1px, transparent 0, transparent 50%)', backgroundSize: '10px 10px' }}></div>
                
                <div className="flex items-center justify-between border-b-2 border-slate-900/10 pb-6 mb-6 relative z-10">
                   <div className="flex items-center gap-3">
                     <ShieldCheck className="w-10 h-10 text-primary" />
                     <div>
                       <div className="text-[10px] font-black tracking-[0.3em] uppercase opacity-60">GOVERNMENT OF INDIA</div>
                       <div className="text-lg font-black leading-tight">POLICE DEPARTMENT</div>
                     </div>
                   </div>
                   <div className="text-right">
                     <div className="text-[10px] font-black uppercase opacity-60">SERIAL NUMBER</div>
                     <div className="font-mono font-bold text-primary">{firNumber}</div>
                   </div>
                </div>

                <div className="space-y-6 relative z-10">
                  <div className="grid grid-cols-2 gap-8">
                    <div>
                      <div className="text-[10px] font-black uppercase opacity-50 mb-1">COMPLAINANT</div>
                      <div className="font-bold border-b border-slate-900/5 pb-2 uppercase">{form.name}</div>
                    </div>
                    <div>
                      <div className="text-[10px] font-black uppercase opacity-50 mb-1">DATETIME OF REPORT</div>
                      <div className="font-bold border-b border-slate-900/5 pb-2 uppercase">{timestamp}</div>
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-black uppercase opacity-50 mb-1">PLACE OF OCCURRENCE</div>
                    <div className="font-bold border-b border-slate-900/5 pb-2 uppercase">{form.location}</div>
                  </div>

                  <div>
                    <div className="text-[10px] font-black uppercase opacity-50 mb-1">INCIDENT SUMMARY</div>
                    <p className="text-sm italic font-medium leading-relaxed bg-slate-50 p-4 rounded-xl border border-slate-900/5">
                      &quot;{form.description}&quot;
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-8 pt-4">
                    <div className="flex flex-col items-center">
                       <div className="w-24 h-24 bg-slate-100 rounded-lg flex items-center justify-center mb-2 border border-slate-900/10">
                         <div className="w-16 h-16 border-2 border-slate-900/20 rounded flex items-center justify-center rotate-3">
                           <span className="text-[8px] font-bold opacity-30 text-center uppercase">OFFICIAL SEAL</span>
                         </div>
                       </div>
                       <div className="text-[8px] font-black uppercase opacity-40">DIGITAL SIGNATURE ID: 8X7F2</div>
                    </div>
                    <div className="flex flex-col justify-end">
                       <div className="flex items-center gap-2 mb-2">
                         <div className="w-2 h-2 rounded-full bg-emerald-500"></div>
                         <span className="text-[10px] font-black uppercase">STATUS: VERIFIED</span>
                       </div>
                       <div className="text-[10px] font-black uppercase opacity-50">E-GOVERNANCE TOKEN: 4920-X12-Q</div>
                    </div>
                  </div>
                </div>
                
                <div className="absolute top-0 right-0 p-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                   <button className="p-2 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 transition-all"><Download size={14}/></button>
                   <button className="p-2 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 transition-all"><Printer size={14}/></button>
                   <button className="p-2 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 transition-all"><Share2 size={14}/></button>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center mt-10">
                <button
                  className="px-8 py-3 rounded-2xl bg-white/5 border border-primary/10 font-bold hover:bg-white/10 transition-all text-slate-600"
                >
                  DOWNLOAD AS PDF
                </button>
                <button
                  onClick={() => setShowTracking(true)}
                  className="px-8 py-3 rounded-2xl bg-slate-950 text-white font-bold hover:brightness-110 transition-all flex items-center justify-center gap-2 shadow-xl"
                >
                  <Navigation size={16} /> TRACK PROGRESS
                </button>
                <button
                  onClick={() => { setSubmitted(false); setForm({ name: "", telegram: "", location: "", description: "" }); }}
                  className="px-8 py-3 rounded-2xl bg-primary text-white font-bold hover:brightness-110 transition-all"
                >
                  FILE NEW COMPLAINT
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
};

const FIRTrackingModal = ({ isOpen, onClose, firId, initialStatus }: any) => {
  const [status, setStatus] = useState(initialStatus);

  useEffect(() => {
    if (!isOpen || !firId) return;

    const pollStatus = async () => {
      try {
        const data = await getFIRById(firId);
        if (data.status) setStatus(data.status);
      } catch (err) {
        console.error("Tracking error:", err);
      }
    };

    pollStatus();
    const interval = setInterval(pollStatus, 3000);
    return () => clearInterval(interval);
  }, [isOpen, firId]);

  const steps = [
    { title: "Complaint Lodged", key: "Active", time: "Instant", desc: "Digital FIR successfully encrypted." },
    { title: "Neural Verification", key: "Active", time: "2m", desc: "Cross-referencing across national criminal registries." },
    { title: "Officer Assigned", key: "Investigating", time: "Live", desc: "Official personnel assigned for ground action." },
    { title: "Active Investigation", key: "Investigating", time: "Live", desc: "Units performing on-site forensic analysis." },
    { title: "Case Resolution", key: "Resolved", time: "Pending", desc: "Final legal clearance and report filing." },
  ];

  const getStepStatus = (stepKey: string, index: number) => {
    if (status === "Resolved") return "completed";
    if (status === "Investigating") {
        if (index < 2) return "completed";
        if (index === 2 || index === 3) return "active";
        return "pending";
    }
    if (status === "Active") {
        if (index === 0) return "completed";
        if (index === 1) return "active";
        return "pending";
    }
    return "pending";
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xl"
        >
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.9, y: 20 }}
            className="bg-white rounded-[2.5rem] p-8 max-w-lg w-full shadow-2xl border border-primary/20 relative overflow-hidden"
          >
            <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-emerald-400 via-primary to-cyan-500"></div>
            
            <div className="mb-8">
               <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-[10px] font-black tracking-widest uppercase mb-3">
                  <Navigation size={10} className="animate-pulse" />
                  Live Tracking ID: {firId}
               </div>
               <h4 className="text-2xl font-black text-slate-900 tracking-tight">System Response Grid</h4>
            </div>

            <div className="space-y-8 relative">
              <div className="absolute left-[19px] top-2 bottom-2 w-0.5 bg-slate-100"></div>

              {steps.map((step, idx) => {
                const stepStatus = getStepStatus(step.key, idx);
                return (
                  <div key={idx} className="flex gap-6 relative z-10">
                    <div className={`w-10 h-10 rounded-2xl flex items-center justify-center shrink-0 border-2 transition-all ${
                      stepStatus === 'completed' ? 'bg-emerald-500 border-emerald-500 text-white' :
                      stepStatus === 'active' ? 'bg-white border-primary text-primary animate-bounce shadow-lg shadow-primary/20' :
                      'bg-white border-slate-200 text-slate-300'
                    }`}>
                      {stepStatus === 'completed' ? <CheckCircle size={18} /> : 
                       stepStatus === 'active' ? <Zap size={18} /> : 
                       <Clock size={18} />}
                    </div>
                    <div className="flex flex-col">
                      <div className="flex items-center gap-3">
                        <span className={`text-sm font-black uppercase tracking-tight ${stepStatus === 'pending' ? 'text-slate-400' : 'text-slate-900'}`}>{step.title}</span>
                      </div>
                      <p className={`text-xs mt-1 leading-relaxed ${stepStatus === 'pending' ? 'text-slate-300' : 'text-slate-500 font-medium'}`}>
                        {stepStatus === 'active' && <span className="text-primary font-bold">CURRENT: </span>}
                        {step.desc}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>

            <button 
              onClick={onClose}
              className="w-full mt-10 py-4 rounded-xl bg-slate-950 text-white font-black text-xs uppercase tracking-[0.2em] hover:bg-slate-800 transition-all shadow-xl"
            >
              EXIT MONITOR
            </button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default ComplaintForm;
