[ivr-menu]
exten => s,1,Answer()
exten => s,n,Set(TIMEOUT(digit)=5)
exten => s,n,Set(TIMEOUT(response)=10)
exten => s,n(loop),Background(main-menu)
exten => s,n,WaitExten(10)

exten => 1,1,Playback(dialpad-guide)
exten => 1,n,Goto(ivr-menu,s,loop)

exten => 2,1,Playback(fir-details)
exten => 2,n,Goto(ivr-menu,s,loop)

exten => 3,1,Playback(calling-constable)
exten => 3,n,Dial(PJSIP/200,60)
exten => 3,n,Goto(ivr-menu,s,loop)

exten => i,1,Playback(invalid-choice)
exten => i,n,Goto(ivr-menu,s,loop)

exten => t,1,Playback(invalid-choice)
exten => t,n,Goto(ivr-menu,s,loop)

[demo-context]
exten => 100,1,Dial(PJSIP/100,30)
exten => 100,n,Hangup()

exten => 200,1,Dial(PJSIP/200,30)
exten => 200,n,Hangup()

exten => 300,1,Dial(PJSIP/300,30)
exten => 300,n,Hangup()

; Echo test
exten => 500,1,Answer()
exten => 500,n,Echo()

; IVR Menu at Extension 400
exten => 400,1,Goto(ivr-menu,s,1)