[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=192.168.137.0/24
local_net=172.17.0.0/16
local_net=127.0.0.1/32
external_media_address=192.168.137.220
external_signaling_address=192.168.137.220

[100]
type=endpoint
context=demo-context
disallow=all
allow=ulaw
allow=alaw
auth=100
aors=100
ice_support=yes
use_avpf=yes
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[100]
type=auth
auth_type=userpass
password=password100
username=100

[100]
type=aor
max_contacts=1
remove_existing=yes

[200]
type=endpoint
context=demo-context
disallow=all
allow=ulaw
allow=alaw
auth=200
aors=200
ice_support=yes
use_avpf=yes
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[200]
type=auth
auth_type=userpass
password=password200
username=200

[200]
type=aor
max_contacts=1
remove_existing=yes

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0

[300]
type=endpoint
context=demo-context
disallow=all
allow=ulaw
allow=alaw
allow=opus
auth=300
aors=300
webrtc=yes
dtls_auto_generate_cert=yes
dtmf_mode=info
ice_support=yes
use_avpf=yes
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[300]
type=auth
auth_type=userpass
password=password300
username=300

[300]
type=aor
max_contacts=1
remove_existing=yes